#!/usr/bin/python3
#	etcbuild - Embedded Toolchain build scripts
#	Copyright (C) 2020-2020 Johannes Bauer
#
#	This file is part of etcbuild.
#
#	etcbuild is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	etcbuild is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with etcbuild; if not, write to the Free Software
#	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#	Johannes Bauer <JohannesBauer@gmx.de>

import os
import sys
import json
import contextlib
import subprocess
from FriendlyArgumentParser import FriendlyArgumentParser
from PackageManager import PackageManager
from BuilderFactory import BuilderFactory

parser = FriendlyArgumentParser(description = "Embedded toolchain build script.")
parser.add_argument("-e", "--envfile", metavar = "filename", action = "append", default = [ ], help = "Specifies an environment file; can be specified multiple times (order matters, later options supersede previous ones). Set of JSON files which define build environment parameters such as the target or installation directory.")
parser.add_argument("-p", "--packages", metavar = "filename", default = "packages.json", help = "Specifies package configuration file. Defaults to %(default)s.")
parser.add_argument("-d", "--package-dir", metavar = "dirname", default = "packages", help = "Specifies subdirectory in which to store downloaded package sources. Defaults to %(default)s.")
parser.add_argument("--disable-verification", action = "store_true", help = "Disables verification of hashes of downloaded files. Not recommended.")
parser.add_argument("-v", "--verbose", action = "count", default = 0, help = "Increases verbosity. Can be specified multiple times to increase.")
parser.add_argument("target", metavar = "target", type = str, nargs = "+", help = "Target(s) to build.")
args = parser.parse_args(sys.argv[1:])

class Builder():
	def __init__(self, args):
		self._args = args
		self._environment = self._get_environment()
		self._pkgs = PackageManager(package_definition_filename = self._args.packages, package_directory = self._args.package_dir)
		self._environment["prefix"] = os.path.realpath(os.path.expanduser(self._environment["prefix"]))
		with contextlib.suppress(FileExistsError):
			os.makedirs(self._environment["prefix"])
		if args.verbose >= 2:
			print("Environment: %s" % (self._environment))
		self._subprocess_env = dict(os.environ)
		self._subprocess_env["PATH"] = self._environment["prefix"] + "/bin:" + self._subprocess_env["PATH"]
		self._subprocess_env["LD_LIBRARY_DIR"] = self._environment["prefix"] + "/lib"
		self._builder_factory = BuilderFactory(environment = self._environment, subprocess_environment = self._subprocess_env)

	def _get_environment(self):
		environment = { }
		for envfile in args.envfile:
			with open(envfile) as f:
				new_env = json.load(f)
			environment.update(new_env)
		return environment

	def build_target(self, target):
		pkg = self._pkgs.get(target)
		print("Downloading: %s-%s" % (pkg["pkgname"], pkg["version"]))
		self._pkgs.retrieve(pkg, verify = self._args.disable_verification)
		print("Building: %s-%s" % (pkg["pkgname"], pkg["version"]))
		builder = self._builder_factory.get(pkg)
		builder.unpack()
		builder.build()
		builder.install()

	def run(self):
		for target in self._args.target:
			self.build_target(target)

builder = Builder(args)
builder.run()
